config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  devise_for :users
  root to: 'home#main'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  validates :title, presence: true
  validates :language, presence: true
  validates :length, presence: true
  validates :created_by_user, presence: true

  belongs_to :created_by_user, class_name: 'User', foreign_key: 'created_by_user_id'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    if current_user.nil?
      redirect_to new_user_session_path
    end

    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)
    @assignment.created_by_user_id = current_user.id
    authorize @assignment

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    authorize @assignment
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    authorize @assignment
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:title, :length, :language)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :length, 'Length (number of words)' %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assignments</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Length (words)</th>
      <th>Language</th>
      <th>Posted By</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= link_to assignment.title, assignment %></td>
        <td><%= assignment.length %></td>
        <td><%= assignment.language %></td>
        <td><%= assignment.created_by_user.email %></td>

        <td>
          <% if policy(assignment).update? %>
            <%= link_to 'Edit', edit_assignment_path(assignment) %>
          <% end %>
        </td>

        <td>
          <% if policy(assignment).destroy? %>
            <%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @assignment.title %>
</p>

<p>
  <strong>Length (words):</strong>
  <%= @assignment.length %>
</p>

<p>
  <strong>Language:</strong>
  <%= @assignment.language %>
</p>

<p>
  <strong>Posted by:</strong>
  <%= @assignment.created_by_user.email %>
</p>

<% if policy(@assignment).update? %>
  <%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<% end %>
<%= link_to 'Back', assignments_path %>

app/views/home/main.html.erb
<h1>Users can...</h1>
<ul>
  <li>Sign up and log in/out</li>
  <li>Post a translation assignment (displaying the title, number of words, and the language)</li>
  <li>View any translation assignment by clicking on its title</li>
  <li>Edit/delete their own assignments (but not others - permissions do not allow it)</li>
  <li>Be redirected if they try to create a new assignment without first logging in</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TranslatorConnect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <header class="page-header">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">TranslatorConnect</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav" style="float: right">
            <li><%= link_to 'Assignments', assignments_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li style=""><%= link_to 'Login', new_user_session_path, method: :get %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path, method: :get %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </header>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>